core/CoDelivery/CoDelivery.Web/Controllers/IntegrationController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CoDelivery.Core.Entities;
using CoDelivery.Core.Infra.IntegrationSystems;
using CoDelivery.Web.Models;

namespace CoDelivery.Web.Controllers
{
    public class IntegrationController : AppController
    {
        private readonly CoDeliveryContext _context;
        private readonly IntegrationSystemFactory _integrationSystemFactory;

        public IntegrationController(CoDeliveryContext context, IntegrationSystemFactory integrationSystemFactory)
        {
            _context = context;
            _integrationSystemFactory = integrationSystemFactory;
        }

        public ActionResult Index()
        {
            var user = _context.Users.GetByUserName(UserName);
            var integrations = new List<Integration>();

            if (user != null && user.Integrations != null)
                integrations = user.Integrations.ToList();

            return View(integrations.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Delete(int id)
        {
            var integration = _context.Integrations.FirstOrDefault(i => i.Id == id);

            return View(integration);
        }

        [HttpPost]
        public ActionResult ConfirmDelete(int id)
        {
            var integration = _context.Integrations.FirstOrDefault(i => i.Id == id);

            _context.Integrations.Remove(integration);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult GetConfigDetails(int id)
        {
            var integration = _context.Integrations.GetById(id);

            if (integration.User.UserName != this.UserName)
                return Json(new { Success = false, Folders = false });

            var folders = integration.GetFolders(_integrationSystemFactory, "/");

            return Json(new { Success = true, Folders = folders }, JsonRequestBehavior.AllowGet);
        }
    }
}

core/CoDelivery/CoDelivery.Web/Views/Integration/Create.cshtml
@{
    ViewBag.Title = "Nova integração";
}

<h2>Criar nova integração:</h2>

<div class="col-md-4">
    <a href="/Dropbox" class="btn btn-default btn-lg col-md-10">Dropbox</a>
</div>
<div class="col-md-4">
    <a href="/Ftp" class="btn btn-default btn-lg col-md-10">Ftp</a>
</div>
<div class="col-md-4">
    <a href="/GitHub" class="btn btn-default btn-lg col-md-10">GitHub</a>
</div>

core/CoDelivery/CoDelivery.Web/Views/Integration/Delete.cshtml
@model CoDelivery.Core.Entities.Integration

@{
    ViewBag.Title = "Excluir";
}

<h2>Deseja realmente excluir?</h2>

@using (Html.BeginForm("ConfirmDelete", "Integration", FormMethod.Post))
{
    <p>Deseja excluir a integração de nome <b>@Model.Name</b></p>
    
    @Html.HiddenFor(i => i.Id)
    
    <a href="/Integration" class="btn btn-default">Voltar</a>
    <input type="submit" value="Excluir" class="btn btn-danger"/>
}

core/CoDelivery/CoDelivery.Web/Views/Integration/Index.cshtml
@model List<CoDelivery.Core.Entities.Integration>

@{
    ViewBag.Title = "Integrações";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>Integrações</h2>
    </div>
    <table class="table">
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.IntegrationSystem.ToString()</td>
                <td class="text-success">
                    <i class="glyphicon glyphicon-check"></i> Ok
                </td>
                <td>
                    <a href="/Integration/Delete/@item.Id">
                        <i class="glyphicon glyphicon-remove"></i> Excluir
                    </a>
                </td>
            </tr>
        }
    </table>

    <div class="panel-footer text-right">
        <a href="/Dashboard" class="btn btn-default">Voltar</a>
        <a href="/Integration/Create" class="btn btn-success">Criar nova</a>
    </div>
</div>