core/CoDelivery/CoDelivery.Web/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI;
using AutoMapper;
using CoDelivery.Core.Entities;
using CoDelivery.Core.Infra.Clients;
using CoDelivery.Core.Infra.IntegrationSystems;
using CoDelivery.Core.Migrations;
using CoDelivery.Web.Models;

namespace CoDelivery.Web.Controllers
{
    public class RecipeController : AppController
    {
        private readonly CoDeliveryContext _context;

        public RecipeController(CoDeliveryContext context)
        {
            Mapper.CreateMap<RecipeModel, Recipe>();
            Mapper.CreateMap<Recipe, RecipeModel>()
                .AfterMap(
                (src, dest) => dest.Integrations = src.IntegrationRecipes.Select(
                    ir => ir.Integration.IntegrationSystem.ToString())
                        .ToList());

            _context = context;
        }

        public ActionResult Index()
        {
            var recipesFromUser = _context.Recipes.Where(r => r.User.UserName == this.UserName).ToList();

            var recipesModel = Mapper.Map<List<Recipe>, List<RecipeModel>>(recipesFromUser);

            return View(recipesModel);
        }

        public ActionResult Create()
        {
            Mapper.CreateMap<Integration, IntegrationModel>();

            var integrations = _context.Integrations.Where(i => i.User.UserName == UserName).ToList();

            var mappedIntegrations = Mapper.Map<List<Integration>, List<IntegrationModel>>(integrations);

            ViewBag.Integrations = mappedIntegrations;


            return View();
        }

        [HttpPost]
        public ActionResult Create(RecipeModel recipeModel)
        {
            if (!ModelState.IsValid)
                return View(recipeModel);

            var recipe = Mapper.Map<RecipeModel, Recipe>(recipeModel);
            recipe.User = _context.Users.First(u => u.UserName == this.UserName);

            _context.Recipes.Add(recipe);

            foreach (var s in recipeModel.IntegrationSettings)
            {
                var integration = _context.Integrations.FirstOrDefault(i => i.Id == s.Key);
                var integrationRecipe = new IntegrationRecipe()
                {
                    Configurations = new Dictionary<string, string> { { "Folder", s.Value } },
                    Integration = integration,
                    Recipe = recipe
                };

                _context.IntegrationRecipes.Add(integrationRecipe);
            }


            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var recipe = _context.Recipes.FirstOrDefault(r => r.Id == id);

            if (recipe != null && recipe.User.UserName != this.UserName)
            {
                ModelState.AddModelError("", "Receita não pertence a este usuário");
                return View();
            }

            var recipeModel = Mapper.Map<Recipe, RecipeModel>(recipe);

            return View(recipeModel);
        }

        [HttpPost]
        public ActionResult Delete(RecipeModel recipeModel)
        {
            var recipe = _context.Recipes.FirstOrDefault(r => r.Id == recipeModel.Id);

            if (recipe != null && recipe.User.UserName != this.UserName)
            {
                ModelState.AddModelError("", "Receita não pertence a este usuário");
                return View();
            }

            var integrationRecipes = _context.IntegrationRecipes.Where(r => r.Recipe.Id == recipe.Id);
            foreach (var ir in integrationRecipes)
            {
                _context.IntegrationRecipes.Remove(ir);
            }
            _context.Recipes.Remove(recipe);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Run(int idRecipe)
        {
            var recipe = _context.Recipes.First(r => r.Id == idRecipe);
            var integrationRecipes = recipe.IntegrationRecipes;
            if (integrationRecipes.Count > 2)
                throw new Exception("Algo não saiu como deveria.");

            var isFirstCycle = true;

            foreach (var ir in integrationRecipes)
            {
                var integrationManager = new IntegrationSystemFactory().Build(ir.Integration.IntegrationSystem,
                    ir.Integration.Settings);

                if (isFirstCycle)
                {
                    var files = integrationManager.GetFiles(ir.Configurations["Folder"]);
                    foreach (var file in files)
                    {
                        var completedPath = string.Format(@"C:\CoDelivery\{0}\{1}", UserName, file.Key);
                        var path = completedPath.Remove(completedPath.LastIndexOf('/') + 1);

                        if (!Directory.Exists(path))
                            Directory.CreateDirectory(path);

                        System.IO.File.Create(completedPath).Close();

                        System.IO.File.WriteAllBytes(completedPath, file.Value);
                    }

                    isFirstCycle = false;
                }
                else
                {
                    var pathName = string.Format(@"C:\CoDelivery\{0}", UserName);
                    DirSearch(pathName, integrationManager, ir);
                }
            }

            return RedirectToAction("Index");
        }

        static void DirSearch(string sDir, IIntegrationSystem integrationManager, IntegrationRecipe ir)
        {
            try
            {
                foreach (var d in Directory.GetDirectories(sDir))
                {
                    foreach (var f in Directory.GetFiles(d))
                    {
                        var fileContent = System.IO.File.ReadAllBytes(f);
                        integrationManager.UploadFile(f.Split('\\').Last(), ir.Configurations["Folder"], fileContent);
                    }
                    DirSearch(d, integrationManager, ir);
                }
            }
            catch
            {
                //Do nothing
            }
        }
    }
}

core/CoDelivery/CoDelivery.Web/Views/Recipe/Create.cshtml
@using CoDelivery.Web.Models
@model RecipeModel

@{
    ViewBag.Title = "Criar receita";
}

<h2>Criar nova receita:</h2>

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-3">
            @Html.EditorFor(m => m.Name)
        </div>
        <div class="col-md-3">
            <label>De</label>
            <select class="form-control" id="integration-from" name="IntegrationSettings[0].key">
                <option>--Selecione a integração--</option>

                @foreach (var item in (List<IntegrationModel>)ViewBag.Integrations)
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
            <hr />
            <div>
                <select class="hidden form-control" id="integration-details-from" name="integrationsettings[0].value"></select>
                <br/>
                <div class="loader hide" id="loader-from"></div>
            </div>
        </div>

        <div class="col-md-1">
            <br/>
            <br/>
            <p class="text-center">
                <i class="glyphicon glyphicon-arrow-right"></i>
            </p>
        </div>

        <div class="col-md-3">
            <label>Para</label>
            <select class="form-control" id="integration-to" name="integrationsettings[1].key">
                <option>--Selecione a integração--</option>

                @foreach (var item in (List<IntegrationModel>)ViewBag.Integrations)
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
            <hr />
            <div>
                <select class="hidden form-control" id="integration-details-to" name="integrationsettings[1].value"></select>
                <br/>
                <div class="loader hide" id="loader-to"></div>
            </div>
        </div>
    </div>

    @Html.ActionLink("Voltar", "Index", "Recipe", new { @class = "btn btn-default" })
    <input type="submit" value="Criar" class="btn btn-primary" />
}


@section scripts{
    <script>

        

        $('#integration-from').change(function () {
            $('#loader-from').removeClass('hide').show(); 


            var integrationId = $(this).val();

            var folders = [];
            $.getJSON("/integration/getconfigdetails/", { id: integrationId })
            .done(function (data) {
                $('#integration-details-from').html("--Selecione a integração--");


                folders = data.Folders;
                for (var i = 0; i < folders.length; i++) {
                    $("#integration-details-from").append('<option value="' + folders[i] + '">' + folders[i] + '</option>');
                }
                $("#integration-details-from").removeClass('hidden').show();
            })
            .fail(function () {
                folders = [];
            }).always(function () {
                $('#loader-from').hide();
            });
        });

        $('#integration-to').change(function () {
            $('#loader-to').removeClass('hide').show();

            var integrationId = $(this).val();

            var folders = [];
            var xhr = $.getJSON("/integration/getconfigdetails/", { id: integrationId });
            xhr.done(function (data) {
                $('#integration-details-to').html("--Selecione a integração--");

                folders = data.Folders;

                for (var i = 0; i < folders.length; i++) {
                    $("#integration-details-to").append('<option value="' + folders[i] + '">' + folders[i] + '</option>');
                }
                $("#integration-details-to").removeClass('hidden').show();
            });
            xhr.fail(function() {
                folders = [];
            });
            xhr.always(function() {
                $('#loader-to').hide();
            });

        });
    </script>
}

core/CoDelivery/CoDelivery.Web/Views/Recipe/Delete.cshtml
@model CoDelivery.Web.Models.RecipeModel

@{
    ViewBag.Title = "Excluir receita";
}

@if (!ViewContext.ViewData.ModelState.IsValid)
{
    <p>ViewContext.ViewData.ModelState[0].Errors[0].ErrorMessage</p>
}
else
{
    <h2>Excluir receita <b>@Model.Name</b>?</h2>

    using (Html.BeginForm("Delete", "Recipe"))
    {
        @Html.HiddenFor(m => m.Id)
        <a href="/recipe" class="btn btn-default">Voltar</a>
        <input type="submit" class="btn btn-danger" value="Excluir" />
    }
}

core/CoDelivery/CoDelivery.Web/Views/Recipe/Index.cshtml
@model List<CoDelivery.Web.Models.RecipeModel>

@{
    ViewBag.Title = "Receitas";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>Receitas</h2>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <td class="col-md-10">Receitas</td>
                <td class="col-md-2">Ações</td>
            </tr>
        </thead>
        <tbody>
            
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="col-md-10">
                            <div class="col-md-3">
                                <h4>@item.Name</h4>
                            </div>
                            <div class="col-md-3">@item.Integrations[0]</div>
                            <div class="col-md-3">==>>></div>
                            <div class="col-md-3">@item.Integrations[1]</div>
                        </td>
                        <td class="col-md-2">
                            @using (Html.BeginForm("Run", "Recipe", FormMethod.Post))
                            {
                                @Html.Hidden("idRecipe", @item.Id)
                                <button type="submit" class="btn btn-success" title="rodar"><i class="glyphicon glyphicon-play"></i></button>
                            }
                            <a href="/recipe/Delete/@item.Id" class="btn btn-danger" title="Excluir">
                                <i class="glyphicon glyphicon-remove"></i>
                            </a>
                        </td>
                    </tr>
                }
                    
        </tbody>
    </table>

    <div class="panel-footer text-right">
        <a href="/Dashboard" class="btn btn-default">Voltar</a>
        <a href="/Recipe/Create" class="btn btn-primary">Criar nova</a>
    </div>
</div>